from pathlib import Path

from pitea.utils import cargar_configuracion


RUTA_PROGRAMA= Path("pitea")

ARCHIVO_CONFIG =RUTA_PROGRAMA/ "configuracion.toml"

RUTA_CACHE_GENERAL= RUTA_PROGRAMA / "cache"

conf = cargar_configuracion(ARCHIVO_CONFIG)

RUTA_CACHE_ESPECIFICA= RUTA_CACHE_GENERAL / f"cache_{conf["contador_cache"]}" 

RUTA_OCULTACION=RUTA_CACHE_ESPECIFICA / "ocultacion"
RUTA_OCULTACION_DATOS= RUTA_OCULTACION / "datos"
RUTA_OCULTACION_IMAGEN= RUTA_OCULTACION / "imagen"
RUTA_OCULTACION_AUDIO= RUTA_OCULTACION / "audio"

RUTA_DATOS_CIFRADO = RUTA_OCULTACION_DATOS / "datos_originales_cifrados.txt"
RUTA_IMAGEN_CONTENEDORA = RUTA_OCULTACION_IMAGEN / "imagen_contenedora.%s"
RUTA_AUDIO_CONTENEDOR = RUTA_OCULTACION_AUDIO / "audio_contenedor.%s"

RUTA_DESOCULTACION=RUTA_CACHE_ESPECIFICA / "desocultacion"
RUTA_DESOCULTACION_DATOS= RUTA_DESOCULTACION / "datos"
RUTA_DESOCULTACION_IMAGEN= RUTA_DESOCULTACION / "imagen"


RUTA_DATOS_CIFRADOS_DESOCULTACION = RUTA_DESOCULTACION_DATOS / "datos_desocultos_originales_cifrados.txt"
RUTA_DATOS_LIMPIOS_DESOCULTACION = RUTA_DESOCULTACION_DATOS / "datos_desocultos_originales_limpios.txt"
RUTA_IMAGEN_DESOCULTACION = RUTA_DESOCULTACION_IMAGEN / "imagen_contenedora_desocultacion.%s"


LISTA_DIR_CACHE_OCULTACION=[RUTA_OCULTACION_DATOS,RUTA_OCULTACION_IMAGEN,RUTA_OCULTACION_AUDIO]

LISTA_DIR_CACHE_DESOCULTACION=[RUTA_DESOCULTACION_DATOS,RUTA_DESOCULTACION_IMAGEN]


SEMILLA = b'\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f\x10'

VERBOSE = False

FORMATO_IMAGEN_DESOCULTACION = "png"


